### PR TITLE
Make dark scroll bar in dark theme

### PR DESCRIPTION
**Pull request by rakleed**

### CODE REVIEW

**Comment by gork7777** [comment]
Users won't be able to see it if dark bar is used in dark theme I guess.

**Comment by rakleed** [comment]
@slavaleleka 

<details><summary>Popup</summary>

Before:
image

After:
image

</details>

<details><summary>Options</summary>

Before:
image

After:
image

</details>

**Comment by kaprielov** [comment]
Vars isn't a good place for a color-scheme. Move it to the common.pcss. And please check how it works when switching the mode from the options page.

**Comment by rakleed** [comment]
@kaprielov done.

Which `VPN_API_URL` and `AUTH_API_URL` do you use in production? Because to switch the theme in options, I need to log in to my account, but for that, I need to specify the correct URLs in `.env`.

**Comment by kaprielov** [comment]
@rakleed 
VPN_API_URL="api.adguard.io" 
AUTH_API_URL="auth.adguard-vpn.com"

**Comment by rakleed** [comment]
@kaprielov now the color of the scroll bar depends only on the system (browser) theme. If I enable a dark theme in the system, the scroll bar remains dark regardless of the theme in the extension's options. The same is actual for a light theme.

But I still think that you should accept this change because users use "System theme" by default, which will work fine.

I also think you should create separate CSS files for light and dark themes in the future.

**Comment by kaprielov** [comment]
@rakleed I suggest adding only `colour-scheme: light dark;` to `:root` to switch in the system. To switch from the options page, add `color-scheme: light` to `.light-mode` and `color-scheme: dark` to `.dark-mode`.

**Comment by rakleed** [comment]
@kaprielov done, and yes, it now works correctly when choosing a dark or light theme.

**Review by kaprielov — APPROVED** [review]

**Comment by kaprielov** [comment]
We accept these changes. 49266da8bc8

**Pull request closed without merging**
